sudo: required
env: 
  # - TRAVIS_PR=$TRAVIS_PULL_REQUEST
  - TRAVIS_PR=2
language: node_js
node_js:
 - '8'
 - '10'
 - '12'
before_script:
 - npm i && npm i -g imgur-upload-cli
 - git stash
 - curl -sL https://raw.githubusercontent.com/stephencelis/ghi/master/ghi > ghi && chmod 755 ghi && sudo mv ghi /usr/local/bin
 - git config --global ghi.token $GH_TOKEN
script:
 - npm start vsnap
after_script:
 - imgur-upload basedir .
 - var=$(imgur-upload vsnap.png)
 - if [ $TRAVIS_PR != false ]; then 
    ghi comment -vm "${TRAVIS_EVENT_TYPE} ${TRAVIS_JOB_ID} ${TRAVIS_JOB_NUMBER} ${var}" $TRAVIS_PR;
    fi;
