sudo: required
language: node_js
node_js:
 - '8'
 - '10'
 - '12'
before_script:
 - npm install
 - curl -sL https://raw.githubusercontent.com/stephencelis/ghi/master/ghi > ghi && chmod 755 ghi && sudo mv ghi /usr/local/bin
 - git config --global ghi.token $GH_TOKEN
 - node ./matcher.js
script:
 - matcher vsnap
#  remember to process.exit() this
after_script:
 - ghi comment -vm "hi from travis 👋" 2
 - ls out
# supply user.repo param?
# upload to server and push link back to issue
