sudo: required
language: node_js
node_js:
 - '8'
 - '10'
 - '12'
before_script:
 - npm i && npm i -g imgur-upload
 - git stash
 - curl -sL https://raw.githubusercontent.com/stephencelis/ghi/master/ghi > ghi && chmod 755 ghi && sudo mv ghi /usr/local/bin
 - git config --global ghi.token $GH_TOKEN
script:
 - npm start vsnap
after_script:
 - imgur-upload basedir .
 - var=$(imgur-upload vsnap.png)
 - if [ $TRAVIS_PULL_REQUEST != false ]; then ghi comment -vm $var $TRAVIS_PULL_REQUEST; else ghi comment -vm $var 2; fi;
